package com.company.logistics.enums;

public enum CommandType {
    CREATEPACKAGE,
    CREATEROUTE,
    ASSIGNPACKAGETOROUTE,
    ASSIGNTRUCKTOROUTE,
    FINDROUTE,
    LISTPACKAGEINFO,
    LISTTRUCKINFO,
    LISTROUTEINFO,
    CHANGESPEEDMODEL,
    DELIVERPACKAGE,
    HELP
}
