package com.company.logistics.enums;

public enum CommandType {
    CREATEPACKAGE,
    CREATEROUTE,
    ASSIGNPACKAGETOROUTE,
    ASSIGNTRUCKTOROUTE,
    FINDROUTE,
    LISTPACKAGEINFO,
    LISTTRUCKINFO,
    LISTROUTEINFO,
    LISTUSERINFO,
    CHANGESPEEDMODEL,
    DELIVERPACKAGE,
    VIEWSPEEDMODEL,
    REMOVEPACKAGEFROMROUTE,
    REMOVETRUCKFROMROUTE,
    LISTROUTESWITHNOTRUCKASSIGNED,
    LISTPACKAGESWITHSTATUS,
    VIEWPACKAGEWITHID,
    LISTUSERWITHROLE,
    CREATEUSER,
    REMOVEUSER,
    LOGIN,
    LOGOUT,
    HELP,
    SAVE,
    LOAD
}
